### ISSUE TITLE
Update `@docusaurus/*` to `2.2.0`

### ISSUE THREAD

**Issue by danisharora099** [acid-info/logos-site-builder#71]
For `waku.guide`, we have now updated all `@docusaurus/*` deps to `2.2.0` for a feature support rolled out in the same.

Though not a breaking change, it's preferred to keep all `docusaurus/*` deps on the same version as `/core`

**Comment by danisharora099** [comment]
Update: it is a breaking change as support for mermaid diagrams was introduced in `2.2.0`.

**Comment by jeangovil** [comment]
Closing this issue as it is not relevant to this repository.
